# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json

name: Deploy

on:
    push:
        branches: ["prod", "dev"]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        container: public.ecr.aws/j5s7c7d2/zenhalab-ci-runner-prod:1
        environment: ${{ github.ref_name == 'prod' && 'prod' || 'dev' }}
        steps:
            - uses: actions/checkout@v4
            - name: Deploy
              env:
                  STAGE: ${{ vars.STAGE }}
                  FRONT_BUCKET_NAME: ${{ vars.FRONT_BUCKET_NAME }}
                  FRONT_CLOUDFRONT_DISTRIBUTION_ID: ${{ vars.FRONT_CLOUDFRONT_DISTRIBUTION_ID }}
                  FRONT_BASE_URL: ${{ vars.FRONT_BASE_URL }}
                  FRONT_BASE_URL_DOMAIN: ${{ vars.FRONT_BASE_URL_DOMAIN }}
                  API_BASE_URL: ${{ vars.API_BASE_URL }}
                  API_BASE_URL_DOMAIN: ${{ vars.API_BASE_URL_DOMAIN }}
                  DYNAMO_URL_TABLE_NAME: ${{ vars.DYNAMO_URL_TABLE_NAME }}
                  GATEWAY_API_NAME: ${{ vars.GATEWAY_API_NAME }}
                  ARTIFACTS_BUCKET_NAME: ${{ vars.ARTIFACTS_BUCKET_NAME }}
                  AWS_PROFILE: ${{ secrets.AWS_PROFILE }}
              run: |
                  git config --global --add safe.directory '*'
                  aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile ${{ secrets.AWS_PROFILE }}
                  aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile ${{ secrets.AWS_PROFILE }}
                  aws configure set region ${{ secrets.AWS_REGION }} --profile ${{ secrets.AWS_PROFILE }}

                  LAST_TAG=$(git rev-list --tags --max-count=1 --skip=1)
                  export NX_BASE="${LAST_TAG:=origin/prod}"

                  yarn install
                  yarn run -- nx run shortener:deploy --configuration=${{ vars.STAGE }} --runner=${{ vars.NX_RUNNER }}
